# Generated by Django 3.0.3 on 2020-03-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reviews_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=5)),
            ],
        ),
    ]
