# Generated by Django 3.0.3 on 2020-03-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_credentials',
            name='username',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
