# Generated by Django 3.0.3 on 2020-03-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_credentials_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='URL',
        ),
        migrations.AddField(
            model_name='reviews',
            name='user',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_credentials',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_credentials',
            name='password',
            field=models.CharField(max_length=1000),
        ),
    ]
